<div class="container">
    <div class="row" id="marketing">
        <div class="out-wrapper">
            
            <?php $this->layout('/header') ?>    

            <div class="container">
                <div class="row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6">
                        <div class="page-wrapper">
                            <h1 class="page-header">Liên hệ</h1>
                            <div class="page-body">
                                <?php $this->layout('message') ?>
                                <form method="POST">
                                    <div class="form-group">
                                        <label class="control-label">Tên bạn</label>
                                        <input type="text" class="form-control" name="name" placeholder="Nhập tên bạn"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Email</label>
                                        <input type="text" class="form-control" name="email" placeholder="Nhập địa chỉ email"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Số điện thoại</label>
                                        <input type="text" class="form-control" name="phone" placeholder="Nhập số điện thoại"/>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label">Nội dung liên hệ</label>
                                        <textarea name="content" rows="10" class="form-control"></textarea>
                                    </div>
                                    <div class="form-group">
                                        <input type="submit" name="submit" value="Liên hệ" class="btn btn-primary"/>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3"></div>
                </div>
            </div>

        <?php $this->layout('/footer') ?>

        </div>
    </div>
</div>