<?php $this->layout('/header') ?>

    <!-- Carousel
        ================================================== -->
    <div class="carousel carousel-cover carousel-cover-min slide" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img class="first-slide" src="<?php echo CUR_MODULE_URL ?>/views/assets/images/cover-min.jpg" alt="Cover">
                <div class="container">
                    <div class="carousel-caption">
                        <form action="<?php echo BASE_URL ?>search">
                            <div class="form-group">
                                <input type="text" name="keyword" class="form-control input-lg" placeholder="Nhập tên bệnh cần tìm"/>
                            </div>
                            <div class="form-group">
                                <button class="btn btn-primary btn-lg" type="submit">Tìm kiếm</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- /.carousel -->

    <div class="container">
        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="page-wrapper">
                    <h1 class="page-header">Liên hệ</h1>
                    <div class="page-body">
                        <?php $this->layout('message') ?>
                        <form method="POST">
                            <div class="form-group">
                                <label class="control-label">Tên bạn</label>
                                <input type="text" class="form-control" name="name" placeholder="Nhập tên bạn"/>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Email</label>
                                <input type="text" class="form-control" name="email" placeholder="Nhập địa chỉ email"/>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Số điện thoại</label>
                                <input type="text" class="form-control" name="phone" placeholder="Nhập số điện thoại"/>
                            </div>
                            <div class="form-group">
                                <label class="control-label">Nội dung liên hệ</label>
                                <textarea name="content" rows="10" class="form-control"></textarea>
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" value="Liên hệ" class="btn btn-primary"/>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>

<?php $this->layout('/footer') ?>