<div class="container">
    <div class="row">
        <div class="out-wrapper">
            <?php
            /**
             * @var \FA\MODELS\M_BENHVATNUOI\diseases $DSS
             * @var array $dss
             */
            ?>
            <?php $this->layout('/header') ?>

                <!-- Carousel
                ================================================== -->
                <div class="carousel carousel-cover slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <img class="first-slide" src="<?php echo CUR_MODULE_URL ?>/views/assets/images/cover2.jpg" alt="Cover">
                            <div class="container">
                                <div class="carousel-caption">
                                    <h1>Tìm kiếm bệnh vật nuôi</h1>

                                    <form action="<?php echo BASE_URL ?>search">
                                        <div class="form-group">
                                            <input type="text" name="keyword" class="form-control input-lg" placeholder="Nhập bệnh cần tìm"/>
                                        </div>
                                        <div class="form-group">
                                            <button class="btn btn-primary btn-lg" type="submit">Tìm kiếm</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- /.carousel -->

                <div class="container">
                    <div class="page-wrapper">
                        <h1 class="page-header">
                            <?php echo $dss['name'] ?>
                            <?php if ($dss['scientific_name']): ?>
                                <small class="scientific_name"><?php echo $dss['scientific_name'] ?></small>
                            <?php endif ?>
                        </h1>

                        <div class="page-body">
                            <div class="row">
                                <div class="col-lg-5">
                                    <div class="page-thumbnail thumbnail">
                                        <img src="<?php echo $dss['full_thumbnail'] ?>"/>
                                    </div>
                                    <?php if ($dss['video']): ?>
                                        <div class="page-video">
                                            <?php $youtube_id = youtube_id($dss['video']) ?>
                                            <iframe width="100%" height="400px" src="https://www.youtube.com/embed/<?php echo $youtube_id ?>" frameborder="0" allowfullscreen></iframe>
                                        </div>
                                    <?php endif ?>
                                </div>
                                <div class="col-lg-7">
                                    <?php if ($dss['description']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Mô tả</h3>
                                            <div class="block-body">
                                                <?php echo $dss['description'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <?php if ($dss['symptoms']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Triệu trứng</h3>
                                            <div class="block-body">
                                                <?php echo $dss['symptoms'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <?php if ($dss['lesions']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Bệnh tích</h3>
                                            <div class="block-body">
                                                <?php echo $dss['lesions'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <?php if ($dss['treatments']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Điều trị</h3>
                                            <div class="block-body">
                                                <?php echo $dss['treatments'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <?php if ($dss['prevention']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Cách phòng tránh</h3>
                                            <div class="block-body">
                                                <?php echo $dss['prevention'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>

                                    <?php if ($dss['related']): ?>
                                        <div class="block">
                                            <h3 class="block-header">Bệnh liên quan</h3>
                                            <div class="block-body">
                                                <?php echo $dss['related'] ?>
                                            </div>
                                        </div>
                                    <?php endif ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            <?php $this->layout('/footer') ?>
        </div>
    </div>
</div>