<div class="container">
    <div class="row" >
        <hr class="featurette-divider">
        <!-- FOOTER -->
        <footer class="footer">
            <p class="pull-right" style="padding-right: 10px;">
                <a href="<?php echo BASE_URL ?>">Trang chủ</a> -
                <a href="<?php echo BASE_URL ?>search">Tìm kiếm</a> -
                <a href="<?php echo BASE_URL ?>contact">Liên hệ</a> -
                <a href="#">Lên đầu trang</a>
            </p>
            <p style="padding-left: 10px;">&copy; 2015 Bệnh Vật Nuôi.</p>
        </footer>
    </div>    
</div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/assets/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>