<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<?php echo $this->data('view_description') ?>"/>
    <meta name="author" content="<?php echo $this->data('view_author') ?>"/>

    <title><?php echo $this->data('view_title') ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo CUR_MODULE_URL ?>/views/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="<?php echo CUR_MODULE_URL ?>/views/assets/style.css" rel="stylesheet"/>
    <link href="<?php echo CUR_MODULE_URL ?>/views/assets/myweb.css" rel="stylesheet"/>

</head>
<body>
<div class="container" id="main">
        <div class="row">

            <div id="header" class="">
                
                <header class="" id="header">
                    <div class="container">
                        <div class="row">

                            <div class="time">
                                
                                <div id="clock">Loading...
                                    <script type="text/javascript">                         
                                        //Clock
                                        function refrClock()
                                        {
                                            var d = new Date();
                                            var s = d.getSeconds();
                                            var m = d.getMinutes();
                                            var h = d.getHours();
                                            var day = d.getDay();
                                            var date = d.getDate();
                                            var month = d.getMonth();
                                            var year = d.getFullYear();
                                            var days = new Array("Chủ nhật","Thứ hai","Thứ 3","Thứ 4","Thứ 5","Thứ 6","Thứ 7");
                                            var months = new Array("1","2","3","4","5","6","7","8","9","10","11","12");
                                            var am_pm;
                                            if (s < 10) { s = "0" + s }
                                            if (m < 10) { m = "0" + m }
                                            if (h > 12) { h-=12; AM_PM = "PM"}
                                            else {AM_PM = "AM"}
                                            if (h < 10) {h = "0" + h}
                                            document.getElementById("clock").innerHTML = days[day] +" -"+" "+date+"/" +months[month] + "/" + year + " - " + h + ":" + m + ":" + s + " " + AM_PM;
                                            setTimeout("refrClock()",1000);
                                        }
                                        refrClock();
                                    </script>
                                </div>

                            </div>                                                      

                        </div>

                        <div class="topnav">
                                
                            <div class="container">
                                <div class="row">                                   
                                    
                                    <div class="header1">
                                        <a href="<?php echo BASE_URL ?>" class="logo1"><span>MY PET</span></a>
                                    </div>      

                                    <img src="<?php echo CUR_MODULE_URL ?>/views/assets/images/cover-min.jpg" alt="">                         
                                </div>
                            </div>

                        </div>

                    </div>
                </header>

            </div>
            <div class="container">
                <div class="row">
                    <nav class="navix" id="nav">
                        <div class="wrap">
                            <a href="#" id="mobilenav">Menu</a>
                            <ul class="sf-menu sf-js-enabled sf-arrows" id="menunav" style="display: block;">
                                <li>
                                    <a class="current" href="<?php echo BASE_URL ?>">Trang chủ</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL ?>disease/species/gia_suc">Bệnh Gia Súc</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL ?>disease/species/gia_cam">Bệnh Gia Cầm</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL ?>disease/species/khac">Bệnh Khác</a>
                                </li>
                                <li>
                                    <a href="<?php echo BASE_URL ?>contact">Hỏi Đáp</a>
                                </li>
                            </ul>
                            <div id="searchnya">
                                <form action="<?php echo BASE_URL ?>search" id="ajax-search-form">
                                    <input name="keyword" type="text" placeholder="Nhập bệnh cần tìm">
                                    <button title="Search" type="submit">Tìm kiếm</button>
                                    <div id="search-result"></div>
                                </form>
                            </div>
                        </div>
                        <div class="bgnya"></div>
                    </nav>
                </div>
            </div>
    </div>
</div>
