<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<?php echo $this->data('view_description') ?>"/>
    <meta name="author" content="<?php echo $this->data('view_author') ?>"/>

    <title><?php echo $this->data('view_title') ?></title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo CUR_MODULE_URL ?>/views/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"/>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="<?php echo CUR_MODULE_URL ?>/views/assets/style.css" rel="stylesheet"/>
</head>
<body>
<div class="navbar-wrapper">
    <div class="container">
        <div class="header">
            <a href="<?php echo BASE_URL ?>" class="logo"><span>MY PET</span></a>
        </div>
        <ul class="menu">
            <li><a href="<?php echo BASE_URL ?>">Trang chủ</a></li>
            <li><a href="benhvatnuoi/species/index/$1">Bệnh gia cầm</a></li>
            <li><a href="benhvatnuoi/species/index/$1">Bệnh gia súc</a></li>
            <li><a href="benhvatnuoi/species/index/$1">Bệnh khác</a></li>
            <li><a href="<?php echo BASE_URL ?>contact">Hỏi - Đáp</a></li>
        </ul>
    </div>
</div>
