<div class="container">
    <div class="row" id="marketing">
        <div class="out-wrapper">
            <?php
            /**
             * @var \FA\MODELS\M_BENHVATNUOI\diseases $DSS
             */
            ?>
            <div class="container">
                <div class="row">
                     <?php $this->layout('/header') ?>
                </div>
            </div>
                      

            <div class="container marketing">    

                <?php $DSS->lists(array('limit' => 4)) ?>
                <?php if ($DSS->has_result('lists')): ?>
                    <hr class="featurette-divider">
                    <div class="row featurette">
                        <?php while ($row = $DSS->fetch('lists')): ?>
                            <div class="col-lg-3 col-xs-6">
                                <div class="thumbnail">
                                    <a href="<?php echo $row['full_url'] ?>">
                                        <img src="<?php echo $row['full_thumbnail'] ?>" alt="<?php echo $row['name'] ?>"/>
                                    </a>
                                    <div class="caption">
                                        <h3 class="caption-title"><a href="<?php echo $row['full_url'] ?>" title="<?php echo $row['name'] ?>"><?php echo $row['name'] ?></a></h3>
                                        <p><?php echo strip_tags($row['description']) ?></p>
                                    </div>
                                </div>
                            </div>
                        <?php endwhile ?>
                    </div>
                <?php endif ?>

                <hr class="featurette-divider">
                

                <!-- Three columns of text below the carousel -->
                <div class="row">
                    <div class="col-lg-4">
                        <img class="img-circle" src="<?php echo CUR_MODULE_URL ?>/views/assets/images/cho.jpg" alt="Bệnh ở chó" width="140" height="140">
                        <h2>Bệnh ở chó</h2>
                        <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <img class="img-circle" src="<?php echo CUR_MODULE_URL ?>/views/assets/images/meo.jpg" alt="Bệnh ở mèo" width="140" height="140">
                        <h2>Bệnh ở mèo</h2>
                        <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
                    </div><!-- /.col-lg-4 -->
                    <div class="col-lg-4">
                        <img class="img-circle" src="<?php echo CUR_MODULE_URL ?>/views/assets/images/tho.jpg" alt="Bệnh ở thỏ" width="140" height="140">
                        <h2>Bệnh ở thỏ</h2>
                        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
                    </div><!-- /.col-lg-4 -->
                </div><!-- /.row -->
                
            </div><!-- /.container -->

            <?php $this->layout('/footer') ?>
        </div>
    </div>
</div>