<?php $this->layout('/manager/header', array('append_header' => '<link href="' . CUR_MODULE_URL . '/views/manager/assets/vendors/bower_components/summernote/dist/summernote.css" rel="stylesheet">')) ?>
    <div class="tile">
        <div class="action-header clearfix">
            <h1 class="ah-label">Thêm loài</h1>
            <ul class="ah-actions actions">
                <li><a href="<?php echo BASE_URL ?>manager/species" title="Trở lại"><i class="zmdi zmdi-arrow-left"></i></a></li>
            </ul>
        </div>
        <div class="t-body tb-padding">
            <?php $this->layout('message') ?>
            <form method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Tên loài</label>
                            <input type="text" class="form-control" name="name" placeholder="Nhập tên loài"/>
                            <div class="help-block pull-right">Ví dụ: Gia súc, Gia cầm...</div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Ảnh minh họa</label>
                            <input type="file" class="form-control" name="thumbnail"/>
                        </div>
                    </div>
                    <div class="col-lg-6"></div>
                </div>
                <div class="form-group">
                    <label class="control-label">Mô tả</label>
                    <textarea name="description" id="description" rows="10" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="submit-add" value="Thêm loài"/>
                    <a href="<?php echo BASE_URL ?>manager/species" class="btn btn-default">Trở lại</a>
                </div>
            </form>
        </div>
    </div>
<?php
$append_footer = '<script src="' . CUR_MODULE_URL . '/views/manager/assets/vendors/bower_components/summernote/dist/summernote.min.js"></script>
<script>
    $(document).ready(function() {
        $("#description").summernote({
            /*
            onKeyup: function(e) {
                $("#description").val($("#description-editor").code());
            },
            */
            height: 150
        });
    });
</script>'
?>
<?php $this->layout('/manager/footer', array('append_footer' => $append_footer)) ?>