</div><!--/.container-->
</section><!--/#content-->
<footer id="footer">
    Copyright © 2015 Bệnh Vật Nuôi
    <ul class="f-menu">
        <li><a href="<?php echo BASE_URL ?>" target="_blank">Trang chủ</a></li>
        <li><a href="<?php echo BASE_URL ?>manager">Trang tổng quan</a></li>
        <li><a href="<?php echo BASE_URL ?>manager/logout">Đăng xuất</a></li>
    </ul>
</footer>

<!-- Older IE Warning Message -->
<!--[if lt IE 9]>
<div class="ie-warning">
    <h1 class="c-white">Warning!!</h1>
    <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
    <div class="iew-container">
        <ul class="iew-download">
            <li>
                <a href="http://www.google.com/chrome/">
                    <img src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/img/browsers/chrome.png" alt="">
                    <div>Chrome</div>
                </a>
            </li>
            <li>
                <a href="https://www.mozilla.org/en-US/firefox/new/">
                    <img src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/img/browsers/firefox.png" alt="">
                    <div>Firefox</div>
                </a>
            </li>
            <li>
                <a href="http://www.opera.com">
                    <img src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/img/browsers/opera.png" alt="">
                    <div>Opera</div>
                </a>
            </li>
            <li>
                <a href="https://www.apple.com/safari/">
                    <img src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/img/browsers/safari.png" alt="">
                    <div>Safari</div>
                </a>
            </li>
            <li>
                <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                    <img src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/img/browsers/ie.png" alt="">
                    <div>IE (New)</div>
                </a>
            </li>
        </ul>
    </div>
    <p>Sorry for the inconvenience!</p>
</div>
<![endif]-->

<!-- Javascript Libraries -->
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>

<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bootstrap-growl/bootstrap-growl.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>

<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/moment/min/moment.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/bootstrap-select/dist/js/bootstrap-select.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/nouislider/distribute/jquery.nouislider.all.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/summernote/dist/summernote.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/typeahead.js/dist/typeahead.bundle.min.js"></script>


<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/chosen_v1.4.2/chosen.jquery.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/fileinput/fileinput.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/input-mask/input-mask.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/farbtastic/farbtastic.min.js"></script>

<!-- Placeholder for IE9 -->
<!--[if IE 9 ]>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
<![endif]-->

<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/js/functions.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/js/demo.js"></script>

<?php if (isset($append_footer)) echo $append_footer; ?>
</body>
</html>