<!DOCTYPE html>
<!--[if IE 9 ]><html class="ie9"><![endif]-->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta charset="UTF-8">

    <title><?php echo $this->data('view_title') ?></title>

    <link href="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/animate.css/animate.min.css" rel="stylesheet">
    <link href="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/material-design-iconic-font/dist/css/material-design-iconic-font.min.css" rel="stylesheet">
    <link href="<?php echo CUR_MODULE_URL ?>/views/manager/assets/css/app.min.css" rel="stylesheet">
</head>
<body class="login-content">
<!-- Login -->
<div class="lc-block toggled" id="l-login">
    <div class="lcb-float"><i class="zmdi zmdi-pin-account"></i></div>

    <form method="POST">
        <?php $this->layout('message') ?>
        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Tên đăng nhập">
        </div>

        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Mật khẩu">
        </div>

        <div class="clearfix"></div>

        <div class="p-relative ">
            <div class="checkbox cr-alt">
                <label class="c-gray">
                    <input type="checkbox" name="remember" value="1">
                    <i class="input-helper"></i>
                    Ghi nhớ tôi
                </label>
            </div>
        </div>
        <input type="submit" class="btn btn-block btn-primary btn-float m-t-25" name="submit-login" value="Đăng nhập"/>
    </form>
</div>

<!-- Older IE Warning Message -->
<!--[if lt IE 9]>
    <div class="ie-warning">
        <h1 class="c-white">Warning!!</h1>
        <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
        <div class="iew-container">
            <ul class="iew-download">
                <li>
                    <a href="http://www.google.com/chrome/">
                        <img src="img/browsers/chrome.png" alt="">
                        <div>Chrome</div>
                    </a>
                </li>
                <li>
                    <a href="https://www.mozilla.org/en-US/firefox/new/">
                        <img src="img/browsers/firefox.png" alt="">
                        <div>Firefox</div>
                    </a>
                </li>
                <li>
                    <a href="http://www.opera.com">
                        <img src="img/browsers/opera.png" alt="">
                        <div>Opera</div>
                    </a>
                </li>
                <li>
                    <a href="https://www.apple.com/safari/">
                        <img src="img/browsers/safari.png" alt="">
                        <div>Safari</div>
                    </a>
                </li>
                <li>
                    <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                        <img src="img/browsers/ie.png" alt="">
                        <div>IE (New)</div>
                    </a>
                </li>
            </ul>
        </div>
        <p>Sorry for the inconvenience!</p>
    </div>
<![endif]-->

<!-- Javascript Libraries -->
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/jquery/dist/jquery.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js"></script>
<!-- Placeholder for IE9 -->
<!--[if IE 9 ]>
    <script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/vendors/bower_components/jquery-placeholder/jquery.placeholder.min.js"></script>
<![endif]-->

<script src="<?php echo CUR_MODULE_URL ?>/views/manager/assets/js/functions.js"></script>
<span class="remove-after"></span>
</body>
</html>