<?php $this->layout('/manager/header') ?>
    <div class="tile">
        <div class="action-header clearfix">
            <h1 class="ah-label">Thêm người quản lý</h1>
            <ul class="ah-actions actions">
                <li><a href="<?php echo BASE_URL ?>manager/accounts" title="Trở lại"><i class="zmdi zmdi-arrow-left"></i></a></li>
            </ul>
        </div>
        <div class="t-body tb-padding">
            <form method="POST">
                <div class="row">
                    <div class="col-lg-6">
                    <?php $this->layout('message') ?>

                        <div class="form-group">
                            <label class="control-label">Tên đầy đủ</label>
                            <input type="text" class="form-control" name="fullname" placeholder="Nhập tên đầy đủ"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Email</label>
                            <input type="text" class="form-control" name="email" placeholder="Nhập email"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Số điện thoại</label>
                            <input type="text" class="form-control" name="phone" placeholder="Nhập số điện thoại"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Tên đăng nhập</label>
                            <input type="text" class="form-control" name="username" placeholder="Tên đăng nhập"/>
                            <div class="help-block pull-right">Chỉ chứa các ký tự a-z 0-9</div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Mật khẩu</label>
                            <input type="password" class="form-control" name="password" placeholder="Nhập mật khẩu"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Xác nhận mật khẩu</label>
                            <input type="password" class="form-control" name="re-password" placeholder="Nhập lại mật khẩu"/>
                        </div>

                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" name="submit-add" value="Thêm người quản lý"/>
                            <a href="<?php echo BASE_URL ?>manager/accounts" class="btn btn-default">Trở lại</a>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Phân quyền cho tài khoản</label>

                        </div>
                        <table class="table permition">
                            <tr>
                                <th>Tên Menu</th>
                                <th>Truy cập</th>
                                <th>Thêm</th>
                                <th>Sửa</th>
                                <th>Xóa</th>
                            </tr>

                            <tr>
                                <td>Quản lý bệnh</td>
                                <td><input type="checkbox" name="permission[]" value="D-R" ></td>
                                <td><input type="checkbox" name="permission[]" value="D-C"></td>
                                <td><input type="checkbox" name="permission[]" value="D-U"></td>
                                <td><input type="checkbox" name="permission[]" value="D-D" ></td>
                            </tr>

                            <tr>
                                <td>Quản lý nhóm bệnh</td>
                                <td><input type="checkbox" name="permission[]" value="G-R"></td>
                                <td><input type="checkbox" name="permission[]" value="G-C" ></td>
                                <td><input type="checkbox" name="permission[]" value="G-U"  ></td>
                                <td><input type="checkbox" name="permission[]" value="G-D"  ></td>
                            </tr>

                            <tr>
                                <td>Quản lý loài</td>
                                <td><input type="checkbox" name="permission[]" value="S-R"></td>
                                <td><input type="checkbox" name="permission[]" value="S-C"></td>
                                <td><input type="checkbox" name="permission[]" value="S-U" ></td>
                                <td><input type="checkbox" name="permission[]" value="S-D"></td>
                            </tr>

                            <tr>
                                <td>Quản lý giống</td>
                                <td><input type="checkbox" name="permission[]" value="B-R" ></td>
                                <td><input type="checkbox" name="permission[]" value="B-C"  ></td>
                                <td><input type="checkbox" name="permission[]" value="B-U" ></td>
                                <td><input type="checkbox" name="permission[]" value="B-D" ></td>
                            </tr>
                        </table>

                    </div>
            </div>

            </form>
        </div>
    </div>
<?php $this->layout('/manager/footer') ?>

<style>
    .permition tr th, .permition tr td{
        border-right: 1px solid #f0f0f0;
        text-align: center;
    }
    .permition > tbody > tr > th{
        border-top: none ;
        border-bottom: 2px solid #3c3c3c ;
    }

    .permition > tbody > tr > th:last-child, .permition > tbody > tr > td:last-child{
        border-right: none ;
    }

</style>
