<?php
/**
 * @var \FA\MODELS\M_BENHVATNUOI\breed $BR
 * @var \FA\MODELS\M_BENHVATNUOI\species $SPC
 */
?>
<?php $this->layout('/manager/header', array('append_header' => '<link href="' . CUR_MODULE_URL . '/views/manager/assets/vendors/bower_components/summernote/dist/summernote.css" rel="stylesheet">')) ?>
    <div class="tile">
        <div class="action-header clearfix">
            <h1 class="ah-label">Chỉnh sửa giống</h1>
            <ul class="ah-actions actions">
                <li><a href="<?php echo BASE_URL ?>manager/breeds" title="Trở lại"><i class="zmdi zmdi-arrow-left"></i></a></li>
            </ul>
        </div>
        <div class="t-body tb-padding">
            <?php $this->layout('message') ?>
            <form method="POST" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="control-label">Chọn loài</label>
                            <?php $SPC->lists(array('get' => 'id, name')) ?>
                            <?php if ($SPC->has_result('lists')): ?>
                                <select name="sid" class="form-control">
                                    <?php while ($species = $SPC->fetch('lists')): ?>
                                        <option value="<?php echo $species['id'] ?>"<?php echo ($species['id'] == $breed['sid'] ? ' selected' : '') ?>><?php echo $species['name'] ?></option>
                                    <?php endwhile ?>
                                </select>
                            <?php else: ?>
                                <p class="form-control-static">Chưa có loài nào. <a href="<?php echo BASE_URL ?>manager/species/add">Thêm loài</a></p>
                            <?php endif ?>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Tên giống</label>
                            <input type="text" class="form-control" name="name" placeholder="Nhập tên giống" value="<?php echo $breed['name'] ?>"/>
                            <div class="help-block pull-right">Ví dụ: Gia súc, Gia cầm...</div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Ảnh minh họa</label>
                            <input type="file" class="form-control" name="thumbnail"/>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <?php if ($breed['full_thumbnail']): ?>
                            <span class="thumbnail"><img src="<?php echo $breed['full_thumbnail'] . '?v=' . time() ?>" class="img-responsive img-rounded"/></span>
                        <?php endif ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label">Mô tả</label>
                    <textarea name="description" id="description" rows="10" class="form-control">
                        <?php echo $breed['description'] ?>
                    </textarea>
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" name="submit-edit" value="Lưu thay đổi"/>
                    <a href="<?php echo BASE_URL ?>manager/breeds" class="btn btn-default">Trở lại</a>
                </div>
            </form>
        </div>
    </div>
<?php
$append_footer = '<script src="' . CUR_MODULE_URL . '/views/manager/assets/vendors/bower_components/summernote/dist/summernote.min.js"></script>
<script>
    $(document).ready(function() {
        $("#description").summernote({
            /*
            onKeyup: function(e) {
                $("#description").val($("#description-editor").code());
            },
            */
            height: 150
        });
    });
</script>'
?>
<?php $this->layout('/manager/footer', array('append_footer' => $append_footer)) ?>