<?php $this->layout('/manager/header') ?>
    <div class="row">
        <div class="col-lg-6">
            <div class="tile">
                <div class="action-header clearfix">
                    <h1 class="ah-label">Xóa nhóm bệnh</h1>
                    <ul class="ah-actions actions">
                        <li><a href="<?php echo BASE_URL ?>manager/diseases_group" title="Trở lại"><i class="zmdi zmdi-arrow-left"></i></a></li>
                    </ul>
                </div>
                <div class="t-body tb-padding">
                    <?php $this->layout('message') ?>
                    <form method="POST">
                        <div class="form-group">
                            <label class="control-label">Tên nhóm bệnh</label>
                            <input type="text" class="form-control" name="name" disabled value="<?php echo $dss['name'] ?>"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Thuộc giống</label>
                            <?php $breed = $BR->data($dss['bid'], 'name, sid') ?>
                            <input type="text" class="form-control" name="name" disabled value="<?php echo (isset($breed['name']) ? $breed['name'] : 'N/A') ?>"/>
                        </div>
                        <div class="form-group">
                            <label class="control-label">Thuộc loài</label>
                            <?php $species = $SPC->data($breed['sid'], 'name') ?>
                            <input type="text" class="form-control" name="name" disabled value="<?php echo (isset($species['name']) ? $species['name'] : 'N/A') ?>"/>
                        </div>
                        <div class="alert alert-warning">
                            Bạn có chắc chắn muốn xóa nhóm bệnh này không?
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary" name="submit-delete" value="Đồng ý xóa"/>
                            <a href="<?php echo BASE_URL ?>manager/diseases_group" class="btn btn-default">Trở lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
<?php $this->layout('/manager/footer') ?>